title: "<p align=\"center\"> Satyam Chatrola </p>"

logo: "/images/satyam_headshot.png?raw=true"

theme: jekyll-theme-minimal

description: >
  <p align="center">
    <a href="pdf/Satyam Chandrakant Chatrola Resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/satyamchatrola">LinkedIn</a> |
    <a href="https://github.com/Nightshade14">GitHub</a> |
    <a href="https://cloudskillsboost.google/public_profiles/8f8d70ce-809c-45e2-b6ba-022e3bc4cf9f">Google Cloud Profile</a>
  </p>
  <p align="justify">
    Hello! I am Satyam Chatrola. I am pursuing MS in Computer Science at New York University (NYU).
    <br>
    As a Data Scientist (with 1+ year of experience) and a Master's student in Computer Science at New York University, I am passionate about exploring and applying cutting-edge AI technologies, such as Transformers, Generative AI, and Large Language Models, to drive innovation and solve complex problems.<br> 
  </p>

  <p align="justify">
    <ul>Skills:
      <li> AI and Big Data: Python, TensorFlow, PyTorch, Generative AI, Recommendation and Search Systems, Diffusion Models, Transformers, LLMs with RAG,<br>
      Prompt Engineering, Computer Vision, Natural Language Processing, PySpark, Hadoop, OpenCV, dlib.</li>
      <li>Web Technologies and Databases: HTML/CSS, JavaScript, NodeJS, REST APIs, MongoDB, PostgreSQL, Apache Solr.</li>
      <li>Others: SQL, Git, Google Cloud Platform, C/C++, Java, System Design, Power BI.</li>
    </ul>
  </p>